CoinAlpha/hummingbot

gateway/package.json
gateway/src/chains/ethereum/uniswap/uniswap.controllers.ts

Feat/use decimal library in Uniswap v2

---

gateway/src/chains/ethereum/ethereum.controllers.ts

feat/return a value of 1 for txStatus when tx are confirmed

---

gateway/setup/create_certs.sh

Based on @martinkou feedback I created a new PR in this repo for creating certs.

Adds sh file to create certs

---

gateway/src/chains/avalanche/avalanche.validators.ts
gateway/src/chains/ethereum/ethereum.validators.ts
gateway/src/chains/solana/solana.requests.ts
gateway/src/chains/solana/solana.validators.ts
gateway/src/services/ethereum-base.ts

Refactor/use of terms public key, address, private key and wallet in user facing text

---

bin/hummingbot.py
hummingbot/client/command/gateway_command.py
hummingbot/core/gateway/__init__.py
hummingbot/core/utils/__init__.py

Create gateway container with unique port numbers for each Hummingbot instance on `gateway create`, to avoid port collision when there're multiple instances.
* Tested `gateway create`, and verified both `conf_global.yml` and Docker container configs have the unique and matching port number set.
[ch23075]

feat / gateway unique port number

---

gateway/src/chains/avalanche/avalanche.ts
gateway/src/chains/ethereum/ethereum.ts
gateway/src/chains/harmony/harmony.ts
gateway/src/chains/solana/solana.ts
gateway/src/network/network.controllers.ts
gateway/src/network/network.requests.ts
gateway/src/network/network.routes.ts
gateway/test/network/network.routes.test.ts
hummingbot/connector/gateway_EVM_AMM.py

Feat/refactor getStatus function

---

gateway/src/network/network.requests.ts
gateway/src/network/network.routes.ts
gateway/test/network/network.routes.test.ts

We need to use mocks instead of actually calling APIs in our unit tests.

Use mocks in testing

---

bin/docker_connection.py
bin/hummingbot.py
bin/hummingbot_quickstart.py
hummingbot/core/gateway/__init__.py

Added logic to automatically detect and start existing gateway v2 container, on Hummingbot start.
[ch23816]

feat / gateway v2 autostart container

---

hummingbot/client/command/gateway_command.py
hummingbot/core/gateway/__init__.py

Added a `reload_certs()` to re-initialize the `GatewayHttpClient` with the appropriate certs.
[sc-23814]

fix/ Gateway Status monitor not responsive

---

gateway/src/services/wallet/wallet.controllers.ts
hummingbot/core/gateway/__init__.py
test/hummingbot/client/ui/test_interface_utils.py
test/hummingbot/core/web_assistant/test_ws_assistant.py

Fixed mixed up get/post methods in GatewayHttpClient, and fixed gateway error on empty wallets.
* Fixed mixed up get/post methods in GatewayHttpClient
* Fixed gateway error on empty wallets.
* Added some background task cleanup logic to fix a few unit test cases that seem to occasionally freeze.
* Done manual tests in debug console.
[ch24075]
[ch24076]

fix / gateway v2 fix mixed methods

---

gateway/setup/create_certs.sh
gateway/setup/generate_conf.sh
hummingbot/client/command/gateway_command.py
hummingbot/core/gateway/__init__.py

- Fix `create_certs.sh` bashscript
- Fix "PEM passphrase" prompt when starting up Hummingbot client
- Fix `gateway connect` command calling `connect()` function from `ConnectCommand`

fix/ Fix several misc issues for Hummingbot<->Gateway integration 

---

hummingbot/connector/gateway_EVM_AMM.py
hummingbot/connector/gateway_in_flight_order.py
hummingbot/connector/in_flight_order_base.pyx
hummingbot/core/gateway/__init__.py

fix/ better error handling in `GatewayEVMAMM`, `GatewayHttpClient` and improve order tracking

---

hummingbot/user/user_balances.py

feat/ improve verbose during strategy preliminary check

---

hummingbot/client/command/gateway_command.py
hummingbot/client/command/start_command.py

fix/ gateway commands lacking adequate validators

---

.github/workflows/workflow.yml
gateway/jest.config.js
gateway/src/chains/ethereum/ethereum.config.ts
gateway/src/chains/ethereum/ethereum.ts
gateway/src/paths.ts
gateway/src/services/config-manager-v2.ts
gateway/src/services/schema/ethereum-gas-station-schema.json
gateway/src/services/schema/ethereum-schema.json
gateway/src/templates/ethereum-gas-station.yml
gateway/src/templates/ethereum.yml

* Only get gas prices from ETH gas station if on Ethereum mainnet.
* Added logic and configs to get gas prices from Ethereum node for testnets.
[ch24745]

fix / gateway v2 testnet gas

---

gateway/src/services/evm.nonce.ts
gateway/src/services/local-storage.ts
gateway/test/chains/ethereum/evm.nonce.test.ts

Fixed lingering `evm-test1.nonce.level` directories after running evm nonce unit tests.
[ch24883]

fix / gateway v2 lingering dirs

---

hummingbot/client/command/gateway_command.py

Add checks to verify that Infura API key when running the `gateway create` command
[sc-24832]

fix/ add checks to verify Infura API key input

---

hummingbot/client/command/gateway_command.py

fix/ `gateway create` not reinitializing GatewayHttpClient with new port number

---

hummingbot/client/command/gateway_command.py
hummingbot/client/command/start_command.py
hummingbot/client/config/config_helpers.py
hummingbot/client/config/fee_overrides_config_map.py
hummingbot/client/config/global_config_map.py
hummingbot/client/config/security.py
hummingbot/client/settings.py
hummingbot/core/utils/gateway_config_utils.py
hummingbot/templates/conf_global_TEMPLATE.yml
hummingbot/user/user_balances.py

This PR addressed the issue of missing `wallet_address` preventing gateway strategies from starting. It also tags along a fix for the connector checks printout (it used to always print the status of the connector even if it's actually green), and an error in the `unlock_wallet` security method.
Started an `amm_arb` strategy successfully.
Simply test that strategies can be started.
[ch25375]
[ch25402]

(fix) Fixes wallet address error and other small bugs.

---

gateway/src/chains/avalanche/avalanche_tokens_fuji.json
gateway/src/templates/avalanche.yml
gateway/src/templates/pangolin.yml
hummingbot/client/performance.py
hummingbot/connector/gateway_EVM_AMM.py
hummingbot/connector/gateway_price_shim.py
hummingbot/core/data_type/trade_fee.py
hummingbot/core/gateway/__init__.py
hummingbot/core/gateway/utils.py
hummingbot/core/rate_oracle/utils.py
hummingbot/strategy/amm_arb/amm_arb.py
hummingbot/strategy/amm_arb/data_types.py
hummingbot/strategy/amm_arb/start.py
test/hummingbot/core/gateway/test_gateway_utils.py

This fixes a few bugs noticed while performing amm_arb tests on Avalanche mainnet. This patch will enable full end-to-end testing on Avalanche / Pangolin.
Major changes:
* Allow debug price shim to be used with mainnet - since there's no easy way to test with Fuji testnet for Pangolin.
* Fixed the low gas limit default on Pangolin on gateway side.
* Make rate oracle automatically unwrap on-chain token symbols (e.g. convert USDT.e -> USDT).
[ch25505]

feat / gateway v2 avax testing

---

hummingbot/strategy/amm_arb/amm_arb.py
hummingbot/strategy/amm_arb/data_types.py

Address issue where strategy keeps issuing arbitrage opportunity despite orders from previous proposal not completely filled.
[sc-25398]
Have `concurrent_orders_submission` set to `False`.
Ensure that both sides of the Proposal is completed before a new Arbitrage Opportunity is found.

fix/ `amm_arb` strategy to wait for both Proposal sides to complete

---

hummingbot/connector/gateway_EVM_AMM.py

* Added back missing allowance update after successful token approvals.
* Tested by following the steps outlined in the Shortcut bug ticket. The amm_arb strategy is now able to go to ready state and start itself after confirming the token approval.
[ch25622]

fix / gateway v2 missing update allowance

---

hummingbot/client/command/gateway_command.py

Fix minor UI issue where prompt is not present when exiting a UI prompt
[sc-25511]
Ensure that reported issue no longer occurs.

fix/ reset UI prompt when returning from within prompts

---

hummingbot/client/command/gateway_command.py

Minor UI fix.
[sc-25722]
Ensure that the prompts for any wallet private key input is hidden in `gateway connect`

fix/ Ensure that all private key inputs in `gateway connect` are hidden

---

test/hummingbot/strategy/amm_arb/test_amm_arb_start.py

This fixes a remaining unit test error in gateway v2 branch.
Fixed unit test error in amm_arb_start.
Running Hummingbot unit tests no longer gives any errors
$ make test

fix / gateway v2 amm start test errors

---

hummingbot/client/ui/layout.py
hummingbot/core/gateway/status_monitor.py

[ch25670]
Started client with gateway off, flag was `STOPPED, OFFLINE`
Started gateway, flag was `RUNNING, OFFLINE`
after a while, flag was `RUNNING, ONLINE`
- Start client with gateway off, flag should be `STOPPED, OFFLINE`
- Started gateway, flag should be `RUNNING, OFFLINE`
- after a while, flag should be `RUNNING, ONLINE`

feat / add connection status to gateway flag

---

gateway/src/services/config-manager-v2.ts

[ch25007]
Added more details for config validations fails. Configs that fail validation due to additional property would now quote the extra parameter that's added and request it be removed manually.
Added extra parameter to config files at random and confirmed  that appropriate errors were raised for each config.
- Add a random entry in any config file.
- Strat gateway and confirm an error due to additional property is raised.

Feat / improve config manager error verbose

---

gateway/src/chains/ethereum/ethereum.controllers.ts
gateway/src/evm/evm.routes.ts
gateway/src/services/error-handler.ts
gateway/src/services/evm.nonce.ts
gateway/src/services/local-storage.ts
gateway/test/chains/avalanche/avalanche.routes.test.ts
gateway/test/chains/ethereum/evm.nonce.test.ts
gateway/test/services/local-storage.test.ts
gateway/test/services/wallet/wallet.routes.test.ts

Isolated changes to `NonceManager`. Should resolve [sc-26811]
Using the new endpoint `/evm//nextNonce` and manual tests, determine that nonces would expire.

(feat) Include nonce expiry in `NonceManager`

---

hummingbot/connector/gateway_EVM_AMM.py
hummingbot/connector/gateway_in_flight_order.py
hummingbot/core/data_type/in_flight_order.py
hummingbot/strategy/amm_arb/amm_arb.py
hummingbot/strategy/amm_arb/data_types.py
test/hummingbot/connector/connector/gateway/test_gateway_in_flight_order.py

Resolves [sc-24379] [sc-24423] [sc-26652]

refactor/ Integrate `ClientOrderTracker` into `GatewayEVMAMM` and fix misc issues
